CrazyGril/CrazyGril/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'CrazyGril.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('rudiment.urls', namespace='rudiment')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^docker/', include('docker.urls', namespace='docker')),
    url(r'^conf/', include('conf.urls', namespace='conf')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^task/', include('task.urls', namespace='task')),
]

CrazyGril/api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'get_asset_info', 'api.views.get_asset_info', name='get_asset_info'),
    url(r'get_sysInfo', 'api.views.get_sysInfo', name='get_sysInfo'),
    url(r'^get_dockerInfo', 'api.views.get_dockerInfo', name='get_dockerInfo'),
    url(r'^test', 'api.views.test', name='test'),
    url(r'^auto_git', 'api.views.auto_git', name='auto_git'),
    url(r'^get_dockerStats', 'api.views.get_dockerStats', name='get_dockerStats'),
    url(r'^auto_git2', 'api.views.auto_git2', name='auto_git2'),
   )

CrazyGril/cmdb/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
urlpatterns = patterns('',

url(r'^image_build', 'cmdb.views.image_build', name='image_build'),
url(r'^asset_info', 'cmdb.views.asset_info', name='asset_info'),
url(r'^asset_add', 'cmdb.views.asset_add', name='asset_add'),
url(r'^asset_edit', 'cmdb.views.asset_edit', name='asset_edit'),
url(r'^asset_del', 'cmdb.views.asset_del', name='asset_del'),
url(r'^asset_show', 'cmdb.views.asset_show', name='asset_show'),
url(r'^idc_info', 'cmdb.views.idc_info', name='idc_info'),
url(r'^idc_add', 'cmdb.views.idc_add', name='idc_add'),
url(r'^idc_cancel', 'cmdb.views.idc_cancel', name='idc_cancel'),
url(r'^group_connect', 'cmdb.views.group_connect', name='group_connect'),
url(r'^group_add', 'cmdb.views.group_add', name='group_add'),
url(r'^ajax_tran_data', 'cmdb.views.ajax_tran_data', name='ajax_tran_data'),
url(r'^idc_show', 'cmdb.views.idc_show', name='idc_show'),
url(r'^idc_edit', 'cmdb.views.idc_edit', name='idc_edit'),
url(r'^idc_del', 'cmdb.views.idc_del', name='idc_del'),
url(r'^idc_dels', 'cmdb.views.idc_dels', name='idc_dels'),
url(r'^group_edit', 'cmdb.views.group_edit', name='group_edit'),
url(r'^ajax_change_group', 'cmdb.views.ajax_change_group', name='ajax_change_group'),
url(r'^group_del', 'cmdb.views.group_del', name='group_del'),
url(r'^get_mongo_infos', 'cmdb.views.get_mongo_infos', name='get_mongo_infos'),
url(r'^wechat', 'cmdb.views.wechat', name='wechat'),
url(r'^alert_tem', 'cmdb.views.alert_tem', name='alert_tem'),
url(r'^create_alertTS', 'cmdb.views.create_alertTS', name='create_alertTS'),
url(r'^dingding_man', 'cmdb.views.dingding_man', name='dingding_man'),
url(r'^wechat_man', 'cmdb.views.wechat_man', name='wechat_man'),


url(r'^wac_man', 'cmdb.views.wac_man', name='wac_man'),

# group_back
# url(r'^group_add', 'cmdb.views.group_add', name='group_add'),
# group_back

)

CrazyGril/cmdb/views.py
#-*- coding:utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import json
import traceback
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from models import ASSET_STATUS,ASSET_TYPE,Host,Idc,HostGroup,alert_temp
from common.utils import tran_code,get_asset_tyst,pages,page_split,dieAsset_info,get_mongoinfos
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def get_mongo_infos(request):
    print "=========="
    print request.body
    hostip = request.POST.get("hostip", "")
    hostname = request.POST.get("hostname","")
    print hostip, hostname
    return HttpResponse("这是走哪了")
    # return render(request, "/charts/auto_get_type.html", locals())
    # if hostip:
    #     mem = get_mongoinfos(hostip,"mem")
    #
    # else:
    #     if hostname:
    #         pass
    #     else:
    #         return HttpResponse("请输入准确值！")


def asset_edit(request):
    if request.method=="GET":
        print "get"
        print request.body
        host_id = request.GET.get("id")
        all_idc = Idc.objects.all()
        print host_id
        res = get_asset_tyst()
        all_status = res[0]
        all_type = res[1]
        host_info = Host.objects.get(id=host_id)
        return render(request, "asset_edit.html", locals())
    if request.method == "POST":
        res = dieAsset_info(request, Host, Idc)
        if res == 1:
            return redirect("/cmdb/asset_info")
        else:
            return HttpResponse(res)



def image_build(request):
    if request.method == "GET":
        print "测试呗，先这么着！！"
        return redirect("/docker/image_build")
        # return render(request,"image_build.html")
    if request.method == "POST":
        print "测试呗，先这么着！！"
        return redirect("/docker/image_build")


def asset_info(request):
    if request.method == "GET":
        try:
            res = get_asset_tyst()
            all_status = res[0]
            all_type = res[1]
            assets_info = Host.objects.all()
            paginator = Paginator(assets_info, 5)
            page = request.GET.get('page', '1')
            currentPage = int(page)
            try:
                print(page)
                assets_infos = paginator.page(page)  # 获取当前页码的记录
            except PageNotAnInteger:
                assets_infos = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
            except EmptyPage:
                assets_infos = paginator.page(paginator.num_pages)
            return render(request, "index.html", locals())
        except Exception:
            print traceback.format_exc()

    if request.method == "POST":
            pass


def asset_add(request):

    if request.method == "GET":
        res = get_asset_tyst()
        all_status = res[0]
        all_type = res[1]
        all_idc = Idc.objects.all()
        print "all_status all_type "
        print all_status,type(all_status)
        print "========"
        print all_type,type(all_type)
        # assets_list, p, assets, page_range, current_page, show_first, show_end, end_page = pages(all_idc, request)
        return render(request,"asset_add_info.html",locals())
    try:
        if request.method == "POST":
            print "=========="
            hostname = request.POST.get('hostname', '')
            n_ip = request.POST.get('n_ip', '')
            w_ip = request.POST.get('w_ip', '')
            os = request.POST.get('os', '')
            cpu_type = request.POST.get('cpu_type', '')
            cpu_num = request.POST.get('cpu_num', '')
            mem = request.POST.get("mem", '')
            disk = request.POST.get("disk", '')
            asset_no = request.POST.get("asset_nu", '')
            asset_status = request.POST.get("asset_status", '').strip()
            asset_type = request.POST.get("asset_type", '').strip()
            sn = request.POST.get("sn", '')
            Manufacturer = request.POST.get("Manufacturer", '')
            idc = request.POST.get("idc", '')
            update_time = request.POST.get("update_time", '')
            msg = request.POST.get("msg")
            print "Manufacturer"
            print Manufacturer
            print hostname,n_ip,w_ip,os,cpu_num,cpu_type,mem,disk,asset_no,asset_status,asset_type,sn,Manufacturer,idc,update_time,msg
            host = Host()
            host.hostname = hostname
            host.ip = n_ip
            host.other_ip = w_ip
            idc_ids = Idc.objects.filter(name=idc).values()[0]["id"]
            host.idc_id = idc_ids
            host.asset_no = asset_no
            host.asset_type = asset_type
            host.status = asset_status
            host.vendor = Manufacturer
            host.up_time = update_time
            host.cpu_model = cpu_type
            host.cpu_num = cpu_num
            host.memory = mem
            host.disk = disk
            host.sn = sn
            host.os = os
            host.memo = msg
            host.save()
            return redirect("/cmdb/asset_info")
            # return HttpResponse("ok")
    except Exception:
        print traceback.format_exc()
        return HttpResponse(traceback.format_exc())

        # return redirect("/cmdb/ass_info")


def asset_del(request):
    if request.method == 'POST':
        try:
            del_id = request.POST.get("asset_id")
            print "del_id"
            print del_id
            if del_id:
                Host.objects.filter(id=del_id).delete()
                return redirect("/cmdb/asset_info")
        except Exception:
            print traceback.format_exc()
    if request.method == 'GET':
        del_id = request.GET.get("id")
        return render(request, "asset_del.html", locals())



def asset_show(request):
    host_id = request.GET.get("id")
    all_idc = Idc.objects.all()
    print host_id
    res = get_asset_tyst()
    all_status = res[0]
    all_type = res[1]
    host_info = Host.objects.get(id=host_id)
    return render(request, "asset_show.html", locals())


def idc_info(request):
    if request.method == "GET":
        try:
            idc_infos = Idc.objects.all()
            return render(request, "idc_show.html", locals())
        except Exception:
            print traceback.format_exc()
            return HttpResponse(traceback.format_exc())
    if request.method == "POST":
        pass






def idc_add(request):
    if request.method == "POST":
        try:
            idc_name = request.POST.get("idc_name","")
            idc_tag = request.POST.get("idc_tag", "")
            idc_add = request.POST.get("idc_add", "")
            idc_tel = request.POST.get("idc_tel", "")
            idc_pic = request.POST.get("idc_pic", "")
            idc_mph = request.POST.get("idc_mph", "")
            idc_tan = request.POST.get("idc_tan", "")
            idc_ip_range = request.POST.get("idc_ip_range", "")
            idc_net = request.POST.get("idc_net", "")
            idc_msg = request.POST.get("idc_msg", "")
            idc_info = Idc()
            idc_info.name = idc_name
            idc_info.ids = int(idc_tag)
            idc_info.address = idc_add
            idc_info.tel = idc_tel
            idc_info.contact = idc_pic
            idc_info.contact_phone = idc_mph
            idc_info.jigui = idc_tan
            idc_info.ip_range = idc_ip_range
            idc_info.bandwidth = idc_net
            idc_info.memo = idc_msg
            idc_info.save()
            return redirect("/cmdb/idc_info")
        except Exception:
            print traceback.format_exc()
            return HttpResponse(traceback.format_exc())
        # idc_info.name = idc_name

    if request.method == "GET":
        return render(request, "idc_add.html")




#form 表单的不同提交形式 //  2018/6/4-16:53
def idc_cancel(request):
    return redirect("/cmdb/idc_info")


def group_connect(request):
    groups = HostGroup.objects.all()
    ip_nu = HostGroup.objects.filter().values("txt")
    print "======="
    print ip_nu
    return render(request, "group_connect.html",locals())


def group_add(request):
    if request.method=="GET":
        host_ip = Host.objects.filter().values("ip","hostname")
        print  "host_ip"
        print host_ip,type(host_ip)
        return render(request, "group_add.html", locals())
    if request.method=="POST":
        print "group add infos=========="
        print request.method

def ajax_tran_data(request):
    try:
        print "zaizhe---"
        group_name = request.POST.get("group_name")
        desc = request.POST.get("des")
        selectedValues = request.POST.get("selectedValues")
        # try:
        HG = HostGroup()
        HG.name= group_name
        HG.desc = desc
        HG.txt = selectedValues.replace("-" , "; ")

        HG.save()
        # print "selectedValuesssssssssssssssssssssss"
        # print selectedValues
        # serlist = selectedValues.split("-")
        # print "serlist============================"
        # print serlist
        # for li in serlist:
        #     host = Host.objects.get(ip=li)
        #     HG.serverList.add(host)
        #     HG.save()

        # except Exception:

        print "group_name", group_name

        print "desc", desc
        data = request.body
        print "data----------------------------------"
        print data
        return  HttpResponse("操作成功！")
        # all=[]
        # thel=[]
        # all = data.split("=")
        # print "all----------------------------------"
        # print all
        # del all[0]
        # del all[-1]
        # for i in all:
        #     thel.append(''.join(i.split("&")[0]).split("%2C"))
        # print thel
        # print type(thel)
        # if thel and len(thel)>0:
        #     for i in thel:
        #         if ''.join(i).replace("." ,"").isdigit():
        #             pass
        #         else:

CrazyGril/cmdb/templates/alert_temp.html
{% extends "rudiment_index.html" %}
{#{% load common_use %}#}
{% block breadcrumb %}报警模板
<span style="margin-left: 20px"></span>

<a href="/cmdb/wechat"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>

{% endblock %}
{% block content %}
    <style type="text/css">
        .query-title {
            height:32px;
            line-height:32px;
            text-align: right;
        }
        .query-input {
            width: 200px!important;
        }
    </style>

    <div class="alert alert-info">
        <i class="fa fa-info-circle"></i> 填写完整阈值,点击创建。</br>
        <i class="fa fa-info-circle"></i> 以下阈值默认是大于值的百分比。</br>

{#            <i class="fa fa-info-circle"></i> 如不需要续期，请到 <a target="_blank" href="http://workflow.cyou-inc.com">OA系统</a> 中进行虚机退回表单操作。</br>#}
        <span class="label label-danger"> 除非删除，否则模板会永久存在。</span>
    </div>
     <div class="row">
        <div class="form form-inline">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-md-3" style="float: left">
                        <div class="col-md-4 query-title">
                            内存:
                        </div>
                        <div class="col-md-8">
                             <input type="text" class="input-text form-control query-input" id="mem"/>
                        </div>
                    </div>
                    <div class="col-md-3"  style="float: left">
                        <div class="col-md-4 query-title">
                            磁盘:
                        </div>
                        <div class="col-md-8">
                             <input type="text" class="input-text form-control query-input" id="df" placeholder="%"/>
                        </div>
                    </div>

                    <div class="col-md-3"  style="float: left">
                        <div class="col-md-4 query-title">
                            负载:
                        </div>
                        <div class="col-md-8">
                            <input type="text" class="input-text form-control query-input" id="upload"/>

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <div class="col-md-4 query-title">
                            I/O(in):
                        </div>
                        <div class="col-md-8">
                             <input type="text" class="input-text form-control query-input" id="in"/>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="col-md-4 query-title">
                            I/O(out):
                        </div>
                        <div class="col-md-8">
                            <input type="text" class="input-text form-control query-input" id="out"/>
                        </div>
                    </div>
                     <div class="col-md-3">
                        <div class="col-md-4 query-title">
                            端口:
                        </div>
                        <div class="col-md-8">
                            <input type="text" class="input-text form-control query-input" id="port"/>
                        </div>
                    </div>


            </div>




                <div class="row">
                    <div class="btn-group col-md-1">

                        <input type="submit" class="btn btn-primary" onclick="create()" value="创建" style="float: right"/>
                    </div>
                </div>
        </div>
          </div>
          </div>


        <div class="row">
            <table class="table" id="table" data-toggle="table"></table>
        </div>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#table").bootstrapTable({
                    showRefresh: true,
                    clickToSelect: true,
                    showColumns: true,
                    showToggle: true,
                    sortable: true,
                    pagination: true,

                    url: '{% url "cmdb:create_alertTS" %}',
                    columns: [{
                        field: "alert_temp",
                        title: "模板名称"
                    }, {
                        field: "create_time",
                        title: "创建时间",
                        sortable: true
                    }, {
                        field: "create_user",
                        title: "创建人"
                    }, {
                        field: "des",
                        title: "模板描述",
                        sortable: true
                    }, {
                        field: "defaults",
                        title: "默认",
                        sortable: true
                    }]
                });
            });


            function create() {
                $("#table").bootstrapTable('showLoading');
                ip = $("#query_ip").val();
                project = $("#query_project").val();
                type = $("#query_type").val();
                time = $("#query_reservationtime").val();
                host_principal = $("#query_host_principal").val();
                source = $("#query_source").val();
                group = $("#query_group").val();
                info = $("#query_info").val();

                data = {
                    'csrftoken': csrftoken,
                    "ip": ip,
                    "project": project,
                    "type": type,
                    "time": time,
                    "host_principal": host_principal,
                    "source": source,
                    "group": group,
                    "info": info
                };

                $.post("", data,
                        function (data) {
                            if (data) {
                                console.log(data);
                                $("#table").bootstrapTable('hideLoading').bootstrapTable('load', data);
                            } else {
                                alert(data);
                                layer.msg('[失败]', {time: 1000});
                            }
                        }, "json");

            }
        </script>

{% endblock %}

CrazyGril/cmdb/templates/group_del.html
<form action="/cmdb/group_del" method="post" class="form form-horizontal" id="form_validation">
    {% csrf_token %}





<div class="text-center">
        <input type="text" name="group_id" class="hidden" value="{{ del_id }}"/>
        <button type="submit" class="btn radius btn-primary" style="margin: 10px 5px">删除</button>
        <button class="btn radius " data-dismiss="modal" aria-hidden="true" style="margin: 10px  5px" >关闭</button>

    </div>

</form>

CrazyGril/cmdb/templates/idc_add.html
{% extends "rudiment_index.html" %}
{% load staticfiles %}
{% load tz %}
{% block breadcrumb %}添加机房信息
<span style="margin-left: 20px"></span>

<a href="/cmdb/idc_info"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>
{% endblock %}




{% block content %}
<!--<form action="{% url 'cmdb:asset_add' %}" name="splitf" method="post" class="form form-horizontal" id="form_validation" enctype="multipart/form-data" >-->
 <form  action="" name="splitf" method="post" class="form form-horizontal" id="form_validation" enctype="multipart/form-data" >
   {% csrf_token %}

<div class="row cl" style="display: none">
        <label class="form-label col-3"><span class="c-red">*</span>hidden</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="{{host_info.id}}" name="idc_id" />
        </div>
    </div>

<div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>机房名称:</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="{{host_info.hostname}}" name="idc_name" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>机房标识</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control"   value="{{host_info.ip}}"  name="idc_tag" />
        </div>
    </div>


       <div class="row cl">
        <label class="form-label col-3">机房地址</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control"  value="{{host_info.other_ip}}"  name="idc_add" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>机房电话</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="{{host_info.os}}"   name="idc_tel"  />
        </div>
    </div>



      <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>机房负责人</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="{{host_info.cpu_model}}"   name="idc_pic"  >
        </div>
   </div>



     <div class="row cl">
        <label class="form-label col-3">移动电话</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="{{host_info.cpu_num}}"   name="idc_mph" />
        </div>
    </div>




      <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>机柜信息</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="{{host_info.memory}}"  name="idc_tan"  />
        </div>
    </div>

       <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>IP 范围</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="{{host_info.disk}}"  name="idc_ip_range"  />
        </div>
    </div>


      <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>机房带宽</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="{{host_info.asset_no}}"  name="idc_net"  />
        </div>
    </div>


       <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>机房备注信息</label>
        <div class="formControls col-7">
                 <input type="textarea"  rows="7" cols="42" class="input-text form-control"  value="{{host_info.sn}}"  name="idc_msg"  />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span></label>
        <div class="formControls col-7">
        <button onclick="sub()" class="btn radius btn-primary ">添加<span class="glyphicon glyphicon-ok"></span></button>
            <span style="margin-left: 5px"></span>
        <button onclick="cancel()" class="btn radius btn-success " >取消<span class="glyphicon glyphicon-remove"></span></button>
        </div>
    </div>



</form>


<script>
    function cancel(){
        document.splitf.action="{% url 'cmdb:idc_cancel' %}";
        document.splitf.submit();
    }

    function sub(){
        document.splitf.action="{% url 'cmdb:idc_add' %}";
        document.splitf.submit();
    }

</script>


{% endblock %}

CrazyGril/cmdb/templates/wechat_man.html
{% extends "rudiment_index.html" %}
{% load staticfiles %}
{% load tz %}
{% block breadcrumb %}微信报警管理
<span style="margin-left: 20px"></span>

<a href="/cmdb/wechat"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>
{% endblock %}



{% block content %}
 <form  action="" name="splitf" method="post" class="form form-horizontal" id="form_validation" enctype="multipart/form-data" >
   {% csrf_token %}

<div class="row cl" style="display: none">
        <label class="form-label col-3"><span class="c-red">*</span>hidden</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="{{host_info.id}}" name="idc_id" />
        </div>
    </div>

<div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>平台名称:</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="微信企业平台 cctv" name="idc_name" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>分组</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control"   value="rancher_alert"  name="idc_tag" />
        </div>
    </div>


       <div class="row cl">
        <label class="form-label col-3">Agentld</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control"  value="1000002"  name="idc_add" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>Secret</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="mcwvGkw......"   name="idc_tel"  />
        </div>
    </div>



      <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>部门ID</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="1"   name="idc_pic"  >
        </div>
   </div>



<div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>CorpID</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="ww497dd961480bfc5a"   name="idc_pic"  >
        </div>
   </div>




       <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>备注信息</label>
        <div class="formControls col-7">
                 <input type="textarea"  rows="7" cols="42" class="input-text form-control"  value="{{host_info.sn}}"  name="idc_msg"  />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span></label>
        <div class="formControls col-7">
        <button onclick="sub()" class="btn radius btn-primary ">添加<span class="glyphicon glyphicon-ok"></span></button>
            <span style="margin-left: 5px"></span>
        <button onclick="cancel()" class="btn radius btn-success " >取消<span class="glyphicon glyphicon-remove"></span></button>
        </div>
    </div>



</form>


<script>
    function cancel(){
        document.splitf.action="{% url 'cmdb:idc_cancel' %}";
        document.splitf.submit();
    }

    function sub(){
        document.splitf.action="{% url 'cmdb:idc_add' %}";
        document.splitf.submit();
    }

</script>


{% endblock %}

CrazyGril/cmdb/templates/wechat_manage.html
{% extends "rudiment_index.html" %}
{% load staticfiles %}
{% load tz %}
{% block breadcrumb %}微信报警管理
<span style="margin-left: 20px"></span>

<a href="/cmdb/wechat"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>
{% endblock %}



{% block content %}
 <form  action="" name="splitf" method="post" class="form form-horizontal" id="form_validation" enctype="multipart/form-data" >
   {% csrf_token %}

<div class="row cl" style="display: none">
        <label class="form-label col-3"><span class="c-red">*</span>hidden</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="{{host_info.id}}" name="idc_id" />
        </div>
    </div>

<div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>平台名称:</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="微信企业平台 cctv" name="idc_name" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>分组</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control"   value="rancher_alert"  name="idc_tag" />
        </div>
    </div>


       <div class="row cl">
        <label class="form-label col-3">Agentld</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control"  value="1000002"  name="idc_add" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>Secret</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="mcwvGkw......"   name="idc_tel"  />
        </div>
    </div>



      <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>部门ID</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="1"   name="idc_pic"  >
        </div>
   </div>



<div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>CorpID</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value="ww497dd96......"   name="idc_pic"  >
        </div>
   </div>




       <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>备注信息</label>
        <div class="formControls col-7">
                 <input type="textarea"  rows="7" cols="42" class="input-text form-control"  value="{{host_info.sn}}"  name="idc_msg"  />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span></label>
        <div class="formControls col-7">
        <button onclick="sub()" class="btn radius btn-primary ">添加<span class="glyphicon glyphicon-ok"></span></button>
            <span style="margin-left: 5px"></span>
        <button onclick="cancel()" class="btn radius btn-success " >取消<span class="glyphicon glyphicon-remove"></span></button>
        </div>
    </div>



</form>


<script>
    function cancel(){
        document.splitf.action="{% url 'cmdb:idc_cancel' %}";
        document.splitf.submit();
    }

    function sub(){
        document.splitf.action="{% url 'cmdb:idc_add' %}";
        document.splitf.submit();
    }

</script>


{% endblock %}