CrazyGril/CrazyGril/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'CrazyGril.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('rudiment.urls', namespace='rudiment')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^docker/', include('docker.urls', namespace='docker')),
    url(r'^conf/', include('conf.urls', namespace='conf')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^task/', include('task.urls', namespace='task')),
]

CrazyGril/api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'get_asset_info', 'api.views.get_asset_info', name='get_asset_info'),
    url(r'get_sysInfo', 'api.views.get_sysInfo', name='get_sysInfo'),
    url(r'^get_dockerInfo', 'api.views.get_dockerInfo', name='get_dockerInfo'),
    url(r'^test', 'api.views.test', name='test'),
    url(r'^auto_git', 'api.views.auto_git', name='auto_git'),
    url(r'^get_dockerStats', 'api.views.get_dockerStats', name='get_dockerStats'),
    url(r'^auto_git2', 'api.views.auto_git2', name='auto_git2'),
   )

CrazyGril/rudiment/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'rudiment.views.rudiment', name='rudiment'),
    url(r'content$', 'rudiment.views.content', name='content'),
    url(r'update_time_line$', 'rudiment.views.update_time_line', name='update_time_line'),
    url(r'project_log$', 'rudiment.views.project_log', name='project_log$'),
    url(r'^feedback', 'rudiment.views.feedback', name='feedback'),
    url(r'^list_feedback', 'rudiment.views.list_feedback', name='list_feedback'),
    url(r'^submit_feedback', 'rudiment.views.feedback_submit', name='submit_feedback'),
    # url(r'^Elk_Create', 'rudiment.views.Elk_Create', name='Elk_Create'),

   )

CrazyGril/rudiment/models.py
from django.db import models

# Create your models here.

CrazyGril/rudiment/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render, render_to_response

# Create your views here.
from django.template import RequestContext



# @login_required(login_url='/oauth/login/')
def rudiment(request):
    return render(request, "rudiment_content.html")


# @login_required(login_url='/oauth/login/')
def content(request):
    return render(request, "rudiment_content.html")


# @login_required(login_url='/oauth/login/')
def update_time_line(request):
    return render(request, "update_time_line.html")


# @login_required(login_url='/oauth/login/')
def project_log(request):
    return render(request, "update_time_line.html")

# @login_required(login_url='/oauth/login/')
def feedback(request):
    print "nimabio"
    return render(request, "feedback.html")

CrazyGril/rudiment/templates/error500.html
{% extends "rudiment_index.html" %}
{% block breadcrumb %}
操作失败
{% endblock %}
{% block content %}
{% load staticfiles %}
<div style="margin-top:20px;">
<p style="font-weight: 800;font-size: x-large;color: darkred">{{ error }}</p>
<span id="time" style="background: #00BFFF">{{ time }}</span>
    秒钟后自动跳转，如果不跳转，请点击下面的链接<a href="{{ nextUrl }}">返回</a>
</div>
{% endblock %}

{% block footjs %}
<script language="JavaScript" type="text/javascript">
    function delayURL(url) {
		var delay = document.getElementById("time").innerHTML;
		if(delay > 0) {
			delay--;
			document.getElementById("time").innerHTML = delay;
		} else {
			location.href = url;
            return false;
		}
		setTimeout("delayURL('" + url + "')", 1000);
	}

    delayURL("{{ nextUrl }}");

</script>
{% endblock %}

CrazyGril/rudiment/templates/feedback.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extracss %}
    <link rel="stylesheet" href="{% static 'multi-select/css/multi-select.css' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap-table/bootstrap-table.min.css' %}">
    <link rel="stylesheet" href="{% static 'daterangepicker/daterangepicker.css' %}">
{% endblock %}
{% block main-navbar %}
    <ul class="navigation main-menu" id="self-menu">
        <li>
            <a href="{% url 'rudiment:feedback' %}" class="navitem"  title="意见反馈"
               data-treeid="0"><i
                    class="menu-icon fa fa-home"></i><span class="mm-text">意见反馈</span></a>
        </li>
        <li>
            <a href="{% url 'rudiment:list_feedback' %}" class="navitem"  title="意见列表"
               data-treeid="0"><i
                    class="menu-icon fa fa-home"></i><span class="mm-text">意见列表</span></a>
        </li>
    </ul>

{% endblock main-navbar %}

{% block content %}

    <script type="text/javascript">

        $(document).ready(function(){
            $.ajaxSetup({
                 data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
            });
        $('#feedback_form').submit(function(){
                var title = $("#title").val();
                var content = $("#content").val();
                if(title!='' && content !=''){
                    $.ajax({
                        type:"POST",
                        data: {title:title, content:content},
                        url: "/submit_feedback", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                        dataType: "html",
                        success: function(result){
                            $("#title").val('');
                            $("#content").val('');
                            if(result==200) {
                                alertify.set('notifier', 'position', 'bottom-right');
                                alertify.success('谢谢反馈！(#^.^#)');
                            }else{
                                alertify.set('notifier','position', 'bottom-right');
                                alertify.error('反馈失败!┭┮﹏┭┮');
                            }
                        },
                        error: function(){
                            alertify.set('notifier','position', 'bottom-right');
                            alertify.error('反馈失败!┭┮﹏┭┮');
                        }
                    });
                }else{
                    alertify.set('notifier','position', 'bottom-right');
                    alertify.error('请填写内容');
                    return false;
                }
                return false;
            });
        });
</script>
    <div class="row">
    <form class="form-horizontal"  method="POST" id="feedback_form">
        {% csrf_token %}
        <legend>意见反馈表</legend>
           <div class="form-group">
              <label class="col-sm-2 control-label" for="title">标题：</label>
              <div class="col-sm-8">
                 <input class="form-control" name="title" id="title" type="text" value=""/>
              </div>
           </div>
           <div class="form-group">
              <label class="col-sm-2 control-label" for="content">内容：</label>
              <div class="col-sm-8">
                   <textarea class="form-control" rows="8" name="content" id="content"></textarea>
              </div>
            </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">提交</button>
            </div>
        </div>
     </form>
    </div>
{% endblock %}

CrazyGril/rudiment/templates/feedback_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extracss %}
    <link rel="stylesheet" href="{% static 'multi-select/css/multi-select.css' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap-table/bootstrap-table.min.css' %}">
    <link rel="stylesheet" href="{% static 'daterangepicker/daterangepicker.css' %}">
{% endblock %}
{% block main-navbar %}
    <ul class="navigation main-menu" id="self-menu">
        <li>
            <a href="{% url 'rudiment:feedback' %}" class="navitem"  title="意见反馈"
               data-treeid="0"><i
                    class="menu-icon fa fa-home"></i><span class="mm-text">意见反馈</span></a>
        </li>
        <li>
            <a href="{% url 'rudiment:list_feedback' %}" class="navitem"  title="意见列表"
               data-treeid="0"><i
                    class="menu-icon fa fa-home"></i><span class="mm-text">意见列表</span></a>
        </li>
    </ul>

{% endblock main-navbar %}
{% block content %}
    <div class="codeView">
        <script type="text/javascript">
            $(document).ready(function () {
                $('#example').dataTable({
                    "bSort": true,
                    "aoColumnDefs": [
                        {"bSortable": false, "aTargets": "unsortable"}
                    ],
                });
            });
        </script>
        <div class="dataTablebox">
            <header>
            <span class="widget-icon">
                <i class="fa fa-table ">
                </i>
     	    </span>
                意见反馈表
            </header>
            <table id="example" class="table display" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th class="unsortable">标题</th>
                    <th>内容</th>
                    <th>时间</th>
                    <th>建议人</th>
                </tr>
                </thead>
                <tbody>
                {% if obj %}
                    {% for item in obj %}
                        <tr class="user{{ item.id }}">
                            <td>{{ item.title }}</td>
                            <td>{{ item.content }}</td>
                            <td>{{ item.create_time }}</td>
                            <td>{{ item.user }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>

        </div>

    </div>
{% endblock %}

CrazyGril/rudiment/templates/index.html
{% load i18n %}
<!DOCTYPE html>
<html class="no-js" lang="zh-cmn-Hans-CN"> <!--<![endif]-->
<html lang="zh-cmn-Hans-CN">
{% load staticfiles %}
<head>
    <meta charset="utf-8"/>
    <meta name="renderer" content="webkit|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <!--<meta name="apple-mobile-web-app-capable" content="yes" />--><!-- home screen app 全屏 -->
    <!--<meta name="apple-mobile-web-app-status-bar-style" content="black" />--><!-- 状态栏 -->
    <title>{% block title %}CYOU Web CMDB{% endblock %}</title>
    <meta name="keywords" content="CYOU Web cmdb">
    <meta name="description" content="">
    <script>
        var contextPath = ".";
        var CKEDITOR_BASEPATH = contextPath + '/';
        var pathname = location.pathname;
        var relativeurl = pathname.substring(CKEDITOR_BASEPATH.length + pathname.length);
        contextPath = relativeurl;
        // var UPLOAD_ACTION_URL = '/./action/save.pagelet';
        /*
         jQuery.fn.outerHTML = function(s) {
         return (s) ? this.before(s).remove() : jQuery("p").append(this.eq(0).clone()).html();
         }
         */
    </script>
    <link rel="shortcut icon" href="{% static 'img/tiny32.png' %}">
    <link rel="stylesheet" href="{% static 'css/validationEngine.jquery.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/alertify.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/alertify.rtl.css' %}" type="text/css"/>

    <link href="{% static 'css/uiengine.ui.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/uiengine.ui.js' %}"></script>

    {% block extracss %}{% endblock %}

    <!--[if lt IE 9]>
		<link href="{% static 'org/tinygroup/publicComponent/css/ie8apply.css' %}" rel="stylesheet" />
		<script src="{% static 'org/tinygroup/publicComponent/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'base.html' %}"></script>
	<![endif]-->
</head>
<body class="theme-default main-menu-animated">
<script>var init = [];</script>
<script src="{% static 'js/setting.js' %}"></script>

<script type="text/javascript">
    jQuery(document).ready(function () {
        var qcloud = {};
        $('[_t_nav]').hover(function () {
            var _nav = $(this).attr('_t_nav');
            clearTimeout(qcloud[_nav + '_timer']);
            qcloud[_nav + '_timer'] = setTimeout(function () {
                $('[_t_nav]').each(function () {
                    $(this)[_nav == $(this).attr('_t_nav') ? 'addClass' : 'removeClass']('nav-up-selected');
                });
                $('#' + _nav).stop(true, true).slideDown(200);
            }, 150);
        }, function () {
            var _nav = $(this).attr('_t_nav');
            clearTimeout(qcloud[_nav + '_timer']);
            qcloud[_nav + '_timer'] = setTimeout(function () {
                $('[_t_nav]').removeClass('nav-up-selected');
                $('#' + _nav).stop(true, true).slideUp(200);
            }, 150);
        });
    });
</script>
<div class="head-v3">
    <div class="navigation-up">
        <div class="navigation-inner">
            <div class="navigation-v3">
                <ul>
                    <li class="nav-up-selected-inpage" _t_nav="home">
                        <a href="#">首页</a>
                    </li>
                    <li class="" _t_nav="product">
                        <a href="#">云产品</a>
                    </li>
                    <li class="" _t_nav="webmanage">
                        <a href="#">web运维</a>
                    </li>
                    <li class="" _t_nav="solution">
                        <a href="#">行业解决方案</a>
                    </li>
                    <li class="" _t_nav="cooperate">
                        <a href="#">合作伙伴</a>
                    </li>
                    <li _t_nav="support">
                        <a href="#">帮助与支持</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="navigation-down">
        <div id="webmanage" class="nav-down-menu menu-1" style="display: none;" _t_nav="webmanage">
            <div class="navigation-down-inner">
                <dl style="margin-left: 100px;">
                    <dt>域名管理</dt>
                    <dd>
                        <a hotrep="hp.header.webmanage.compute1" href="{% url 'webmanage:domain_list' %} ">二级域名</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.webmanage.compute2" href="{% url 'webmanage:subdomain_list' %} ">三级域名</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.webmanage.compute3"
                           href="{% url 'webmanage:record_detail_list' %}">记录详情</a>
                    </dd>
                </dl>
                <dl>
                    <dt>防火墙管理</dt>
                    <dd>
                        <a hotrep="hp.header.webmanage.storage1" href="{% url 'firewall:project_list' %}">防火墙管理</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.webmanage.storage4" href="{% url 'firewall:task_dispense' %}">防火墙下发</a>
                    </dd>
                </dl>
                <dl>
                    <dt>配置文件管理</dt>
                    <dd>
                        <a hotrep="hp.header.webmanage.monitoring1" href="{% url 'confmanage:conftemplate_list' %} ">配置文件模板</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.webmanage.monitoring2" href="#">业务配置文件</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.webmanage.monitoring3" href="#">配置文件下发</a>
                    </dd>
                </dl>

            </div>
        </div>
        <div id="product" class="nav-down-menu menu-1" style="display: none;" _t_nav="product">
            <div class="navigation-down-inner">
                <dl style="margin-left: 100px;">
                    <dt>计算机与网络</dt>
                    <dd>
                        <a hotrep="hp.header.product.compute1" href="#">云服务器</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.compute2" href="#">弹性Web引擎</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.compute3" href="#">负载均衡</a>
                    </dd>
                </dl>
                <dl>
                    <dt>存储与CDN</dt>
                    <dd>
                        <a hotrep="hp.header.product.storage1" href="#">云数据库</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.storage2" href="#">NoSQL高速存储</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.storage4" href="#">对象存储服务(beta)</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.storage3" href="#">CDN</a>
                    </dd>
                </dl>
                <dl>
                    <dt>监控与安全</dt>
                    <dd>
                        <a hotrep="hp.header.product.monitoring1" href="#">云监控</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.monitoring2" href="#">云安全</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.monitoring3" href="#">云拨测</a>
                    </dd>
                </dl>
                <dl>
                    <dt>数据分析</dt>
                    <dd>
                        <a hotrep="hp.header.product.analysis1" href="#">腾讯云分析</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.analysis2" href="#">关键因子</a>
                    </dd>
                </dl>
                <dl>
                    <dt>开发者工具</dt>
                    <dd>
                        <a hotrep="hp.header.product.devtool1" href="#">移动加速</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.devtool2" href="#">应用加固</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.devtool3" href="#">信鸽推送</a>
                    </dd>
                </dl>
                <dl>
                    <dt>开发者服务</dt>
                    <dd>
                        <a hotrep="hp.header.product.service1" href="#">安全认证服务</a>
                    </dd>
                    <dd>
                        <a hotrep="hp.header.product.service2" href="#">域名备案</a>
                    </dd>
                </dl>
            </div>
        </div>
        <div id="solution" class="nav-down-menu menu-3 menu-1" style="display: none;" _t_nav="solution">
            <div class="navigation-down-inner">
                <dl style="margin-left: 380px;">
                    <dd>
                        <a class="link" hotrep="hp.header.solution.1" href="#">微信</a>
                    </dd>
                </dl>
                <dl>
                    <dd>
                        <a class="link" hotrep="hp.header.solution.2" href="#">游戏</a>
                    </dd>
                </dl>
                <dl>
                    <dd>
                        <a class="link" hotrep="hp.header.solution.3" href="#">移动应用</a>
                    </dd>
                </dl>
            </div>
        </div>
        <div id="support" class="nav-down-menu menu-3 menu-1" style="display: none;" _t_nav="support">
            <div class="navigation-down-inner">
                <dl style="margin-left: 610px;">
                    <dd>
                        <a class="link" hotrep="hp.header.support.1" href="#">资料库</a>
                    </dd>
                </dl>
                <dl>
                    <dd>
                        <a class="link" hotrep="hp.header.support.2" href="#">论坛</a>
                    </dd>
                </dl>
                <dl>
                    <dd>
                        <a class="link" hotrep="hp.header.support.3" href="#">亿元扶持</a>
                    </dd>
                </dl>
            </div>
        </div>
        <div id="cooperate" class="nav-down-menu menu-3 menu-1" style="display: none;" _t_nav="cooperate">
            <div class="navigation-down-inner">
                <dl style="margin-left: 480px;">
                    <dd>
                        <a hotrep="hp.header.partner.1" href="#">代理商</a>
                    </dd>
                </dl>
                <dl>
                    <dd>
                        <a hotrep="hp.header.partner.2" href="#">微信服务商</a>
                    </dd>
                </dl>
                <dl>
                    <dd>
                        <a hotrep="hp.header.partner.3" href="#">创投机构</a>
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>
</body>
</html>

CrazyGril/rudiment/templates/rudiment_content.html
{% extends "rudiment_index.html" %}
{% block content %}
<script type="text/javascript">
    $(function() {
        pageSetUp();
    });
</script>
<div class="mainPage">
    <div class="headerTitle">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h2 class="nav-title"><i class="fa navTitleIcon"></i> 欢迎登陆 <span>&gt; {{ username }}</span></h2>
        </div>
    </div>
</div>
{% endblock %}

CrazyGril/rudiment/templates/success.html
{% extends "rudiment_index.html" %}
{% block breadcrumb %}
操作成功
{% endblock %}
{% block content %}
{% load staticfiles %}
<div style="margin-top:50px;font-weight: 800;font-size: large">
<p>{{ success }}</p>
<span id="time" style="background: #00BFFF">{{ time }}</span>
    秒钟后自动跳转，如果不跳转，请点击下面的链接<a href="{{ nextUrl }}">返回</a>
</div>
{% endblock %}
{% block footjs %}
<script language="JavaScript" type="text/javascript">
    function delayURL(url) {
		var delay = document.getElementById("time").innerHTML;
		if(delay > 0) {
			delay--;
			document.getElementById("time").innerHTML = delay;
		} else {
			location.href = url;
            return false;
		}
		setTimeout("delayURL('" + url + "')", 1000);
	}

    delayURL("{{ nextUrl }}");

</script>
{% endblock %}

CrazyGril/rudiment/templates/update_time_line.html
{% extends "rudiment_index.html" %}
{% block breadcrumb %}
Cctv央视 运维平台更新时间轴
{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="codeView">
    <!-- 代码 开始 -->
    <div class="head-warp">
        <div class="headSty">
            <div class="nav-box">
                <ul>
                    <li class="cur " style="text-align:center; font-size:38px; font-family:'微软雅黑'">
                        Cctv央视 运维平台更新时间轴
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="mainBox">
        <div class="history">
            <div class="history-date">
                       <ul>
                    <h2 id="date03" class="">
                        <a href="#">
                            2018年 </a>
                    </h2>
                           <li class="green">
                        <h3>04.10<span>2018</span></h3>
                        <dl>
                            <dt>
                                更新运维自动化平台
                                <span>1、搭建总体框架</span>
                                <span>2、架构自动化平台功能</span>
                            </dt>
                        </dl>
                    </li>
                            <li>
                        <h3>05.23<span>2018</span></h3>
                        <dl>
                            <dt>
                                更新运维自动化平台
                                <span>1、docker自动build功能开发</span>
                                <span>2、自动上传dockerfile镜像打包</span>
                            </dt>
                        </dl>
                    </li>


{#                           <li>#}
{#                        <h3>01.23<span>2018</span></h3>#}
{#                        <dl>#}
{#                            <dt>#}
{#                                更新运维自动化平台#}
{#                                <span>1、新增VPC管理功能优化</span>#}
{#                                <span>2、阿里云和腾讯云多平台多账号操作管理VPC</span>#}
{#                            </dt>#}
{#                        </dl>#}
{#                    </li>#}


                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}