CrazyGril/CrazyGril/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'CrazyGril.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('rudiment.urls', namespace='rudiment')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^docker/', include('docker.urls', namespace='docker')),
    url(r'^conf/', include('conf.urls', namespace='conf')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^task/', include('task.urls', namespace='task')),
]

CrazyGril/api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'get_asset_info', 'api.views.get_asset_info', name='get_asset_info'),
    url(r'get_sysInfo', 'api.views.get_sysInfo', name='get_sysInfo'),
    url(r'^get_dockerInfo', 'api.views.get_dockerInfo', name='get_dockerInfo'),
    url(r'^test', 'api.views.test', name='test'),
    url(r'^auto_git', 'api.views.auto_git', name='auto_git'),
    url(r'^get_dockerStats', 'api.views.get_dockerStats', name='get_dockerStats'),
    url(r'^auto_git2', 'api.views.auto_git2', name='auto_git2'),
   )

CrazyGril/task/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^test', 'task.views.tasks', name='test'),
    url(r'^bb', 'task.views.testmk', name='test1'),
    url(r'^shell_add', 'task.views.shell_add', name='shell_add'),
    url(r'^ajax_get_range', 'task.views.ajax_get_range', name='ajax_get_range'),
    url(r'^shell_exe', 'task.views.shell_exe', name='shell_exe'),
    url(r'^because_accres', 'task.views.because_accres', name='because_accres'),
    url(r'^show_tasks', 'task.views.show_tasks', name='show_tasks'),
    url(r'^ajax_show_tasks', 'task.views.ajax_show_tasks', name='ajax_show_tasks'),
    url(r'^ajax_upload', 'task.views.ajax_upload', name='ajax_upload'),
    url(r'^upf', 'task.views.upf', name='upf'),
    url(r'^tun_upf', 'task.views.tun_upf', name='tun_upf'),
    url(r'^ansible_show', 'task.views.ansible_show', name='ansible_show'),


   )

CrazyGril/task/models.py
from django.db import models

# Create your models here.

CrazyGril/task/views.py
#-*- coding:utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import json
import traceback
from django.http import HttpResponse
# from CrazyGril import tasks
from .tasks import run_test_suit,mk,seleid,selegroup,idse,segroup,idsecq,uf
# from celery.five import python_2_unicode_compatible
# from celery import five
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from docker.models import dockerHost,DockerStat,dockerStats
from common.get_mongo import *
import time
import os
from common.utils import curpwd,jujfile
from cmdb.models import Host
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from cmdb.models import HostGroup,Idc

def upf(request):

    return render(request,"upf.html",locals())
def tun_upf(request):
    try:
        uploadf = request.FILES.get("uploadf")
        shell = curpwd() + "/upFileShell"
        res = jujfile(shell)
        if res:
            pass
        else:
            os.mkdir(shell)
        filename = shell + "/" + str(uploadf)
        print "=============="
        print filename
        with open(filename, "wb+") as f:
            for chunk in uploadf.chunks():
                f.write(chunk)
        # return HttpResponse("32")
        return render(request,"shell_add.html",locals())
    except Exception:
        print traceback.format_exc()



@csrf_exempt
def ajax_upload(request):
    try:
        ac_name = request.POST.get("ac_name", "")
        uploadf = request.FILES.get("uploadf")
        shell = curpwd() + "/upFileShell"
        res = jujfile(shell)
        if res:
            pass
        else:
            os.mkdir(shell)
        filename = shell + "/" + ac_name
        print "=============="
        print filename
        with open(filename, "wb+") as f:
            for chunk in uploadf.chunks():
                f.write(chunk)
        return HttpResponse("32")
    except Exception:
        print traceback.format_exc()

@csrf_exempt
def because_accres(request):
    try:
        print "because_accres"
        print request.body
        option = request.POST.get("sele", "")
        selectip = request.POST.get("selectip", "")
        rag = request.POST.get("rag", "")
        shell_command = request.POST.get("shell_command", "")
        uploadf = request.FILES.get("uploadf")
        ac_name = request.POST.get("ac_name","")
        print "名称===="
        print ac_name,option,selectip,rag,shell_command,ac_name,uploadf
        if uploadf:
            shell = curpwd() + "/upFileShell"
            res = jujfile(shell)
            if res:
                pass
            else:
                os.mkdir(shell)
            filename = shell + "/" + str(uploadf)
            print "=============="
            print filename
            with open(filename, "wb+") as f:
                for chunk in uploadf.chunks():
                    f.write(chunk)
        if selectip and uploadf:
            print "在这"
            print "/data/" + str(uploadf)
            # selectip, shell_command, copy_command, q_command, name
            copy_command = "src=/cg/cg/CrazyGril/upFileShell/{0} dest=/data/  mode=0755".format(str(uploadf))
            q_command = "/data/" + str(uploadf)
            print "############################################################"
            print q_command
            print "q_command"
            idsecq.delay(selectip,shell_command,copy_command,q_command,ac_name)
            return redirect("/task/shell_add")


        if uploadf:
            copy_command = "src=/cg/cg/CrazyGril/upFileShell/{0} dest=/data/  mode=0755".format(str(uploadf))
            q_command = "/data/" + str(uploadf)
            uf.delay(selectip,shell_command,copy_command,q_command,ac_name)
            return redirect("/task/shell_add")


        if selectip:
            print "this is selectip=========="
            print selectip, shell_command
            res = idse.delay(selectip, shell_command,ac_name)
            if res.successful():
                print "this task is success"
            return redirect("/task/show_tasks")
            # return render(request, "show_tasks.html", locals())
            # return HttpResponse(res)
        else:
           if option == "机房":
               idss = []
               res = Idc.objects.filter(name=rag).values()[0]["id"]
               hh = Host.objects.filter(idc_id=res).values()
               for i in hh:
                   idss.append(i["ip"].encode('raw_unicode_escape'))
               print idss, type(idss)
               res = segroup.delay(idss, shell_command)
               return HttpResponse("option")
           if option == "组":
               idss = []
               res = Idc.objects.filter(name=rag).values()[0]["id"]
               hh = Host.objects.filter(idc_id=res).values()
               for i in hh:
                   idss.append(i["ip"].encode('raw_unicode_escape'))
               print idss, type(idss)
               res = segroup.delay(idss, shell_command)
               return HttpResponse("option")

    except Exception:
        print traceback.format_exc()





def shell_add(request):
    group = HostGroup.objects.all()
    idc = Idc.objects.all()
    # return render(request, "shell_add.html", locals())
    return render(request, "shell_add1.html",locals())

def shell_exe(request):
    try:
        option =request.POST.get("sele","")
        selectip=request.POST.get("selectip","")
        rag = request.POST.get("rag","")
        shell_command=request.POST.get("shell_command","")
        upload_sh=request.POST.get("upload_sh","")
        msg=request.POST.get("msg","")
        if selectip:
            print selectip,shell_command,upload_sh,msg
            seleid.delay(selectip,shell_command)
            return HttpResponse("selectip cancel!")
        else:
            selegroup.delay(option,rag,shell_command,upload_sh,msg)
            print  option,rag,shell_command,upload_sh,msg
            return HttpResponse("option cancel!")
    except Exception:
        print traceback.format_exc()

def ajax_get_range(request):
    try:
        print "request.body ajax"
        print request.body
        types = request.POST.get("range")
        if types == "1":
            return HttpResponse("1")
        if types == "2":
            idc = Idc.objects.all().values()
            print "idc", idc
            all_gn = []
            for i in idc:
                all_gn.append(i["name"])
            print "all_gn"
            print all_gn, type(all_gn)
            print json.dumps(all_gn)
            return HttpResponse(json.dumps(all_gn))
        if types == "3":
            group = HostGroup.objects.all().values()
            print "group",group
            all_gn = []
            for i in group:
                all_gn.append(i["name"])
            print "all_gn"
            print all_gn,type(all_gn)
            print json.dumps(all_gn)
            return HttpResponse(json.dumps(all_gn))
        if types == "default":
            print "here default!!!"
            return HttpResponse("default")
    except Exception:
        print traceback.format_exc()
    # return HttpResponse("rehi")


def testmk(request):
    print "开始创建文件夹"
    result = mk.delay()
    print result,type(result)
    return HttpResponse("异步五秒")

def tasks(request):
    print('before run_test_suit')
    result = run_test_suit.delay('110')
    print('after run_test_suit')
    return HttpResponse("job is runing background~")



from django_celery_results.models import TaskResult
def show_tasks(request):
    return render(request,"show_tasks.html")




def ajax_show_tasks(request):
    try:
        res = TaskResult.objects.all().values()
        print "sssss"
        print res
        re= []
        for i  in res:
            print i["date_done"]
            print type(i["date_done"])
            result ={}
            result["status"] = i["status"]
            result["date_done"] = "2017"
            result["traceback"] = i["traceback"]
            result["result"] = i["result"]
            result["content_type"] = i["content_type"]
            result["content_encoding"] = i["content_encoding"]
            result["task_id"] = i["task_id"]

            re.append(result)
            print "rrrrrrr"
            print re
        return HttpResponse(json.dumps(re))
    except Exception:
        print traceback.format_exc()
def ansible_show(request):
    return render(request,"ansible_add.html",locals())

CrazyGril/task/templates/ansible_add.html
{% extends "rudiment_index.html" %}
{% load staticfiles %}
{% load tz %}
{% block breadcrumb %}ansible
<span style="margin-left: 20px"></span>

<a href="/cmdb/idc_info"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="alert alert-info">
            <i class="fa fa-info-circle"></i> 以下填写只能是ansible 命令。</br>
            <i class="fa fa-info-circle"></i> 以下操作会进行日志保存。</br>
            <span class="label label-danger"> 以下选择范围会根据选择方式自动获取。</span>

        </div>
    </div>

 <form  action="/task/because_accres" name="splitf" method="post" class="form form-horizontal" id="form_ids" enctype="multipart/form-data" >
   {% csrf_token %}

<div class="row cl" style="display: none">
        <label class="form-label col-3"><span class="c-red">*</span>hidden</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="{{host_info.id}}" name="idc_id" />
        </div>
    </div>


    <div class="row cl">
        <label class="form-label col-3"><span  class="c-red">*</span>执行名称</label>
        <div class="formControls col-7">
                 <input type="text"   class="input-text form-control"  value="{{host_info.sn}}"  name="ac_name"  id="ac_name" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>选择方式</label>
        <div class="formControls col-7">
            <select class="form-control" name="sele" id="MySelect">
                <option name="default">-------------</option>
                <option name="1">主机ip</option>
                <option name="2">机房</option>
                <option name="3">组</option>
            </select>
        </div>
    </div>



    <div  id = "selectrange" class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>选择范围</label>
        <div class="formControls col-7">
            <select class="form-control" name="rag" id="van" >

            </select>
        </div>
    </div>


      <div  id = "selectip"  style="display: none" class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>选择IP</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value=""   name="selectip"  />
        </div>
    </div>





       <div class="row cl">
        <label class="form-label col-3"><span class="c-red" >*</span>ansible 命令</label>
        <div class="formControls col-7">
            <textarea  id = "shell_command" name="shell_command" class="form-control" rows="5"></textarea>

        </div>
    </div>



      <div class="row cl">
        <label class="form-label col-3">上传playbook</label>
        <div class="formControls col-7">
{#            <a  class="input-text form-control btn btn-primary" onclick="alink()" modal-title="上传shell 文件" data-target="#add" data-toggle="modal" data-height="330" data-width="700"#}
{#               href="/task/upf">#}
{#                上传dockerfile -- {{ filename }}#}
{#            </a>#}
{#            <input type="text" class="input-text form-control"   value=""   name="upload_sh"  />#}
         <input type="file" class="input-text form-control btn btn-success"   value=""   name="uploadf"  />
        </div>
    </div>


   <div id="add" class="modal hide fade " tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <span class="glyphicon glyphicon-fullscreen"></span>
                <span class="close" data-dismiss="modal" aria-hidden="true"><i class="glyphicon glyphicon-remove "></i></span>

                <h3>对话框标题</h3>
            </div>
            <div class="modal-body"></div>

        </div>



   <div class="row cl">
        <label class="form-label col-3"></label>
        <div class="formControls col-7">
        <button onclick="sub()" class="btn radius btn-primary ">执行<span class="glyphicon glyphicon-ok"></span></button>
            <span style="margin-left: 5px"></span>
        <button onclick="cancel()" class="btn radius btn-success " >取消<span class="glyphicon glyphicon-remove"></span></button>
        </div>
    </div>



</form>


<script>
    function cancel(){
        document.splitf.action="{% url 'task:shell_exe' %}";
        document.splitf.submit();
    }



    $("#MySelect").change(function(){
        $("#van").empty();
        var opt = $("#MySelect option:selected").attr("name");
         $("#selectip").hide()
         $("#selectrange").show()

        if (opt == "1"){
             $("#selectip").show()
             $("#selectrange").hide()
        }


        var datas = {
            'csrftoken': csrftoken,
            'range':opt
        };
        $.ajax({
            type:"POST",
            url:"/task/ajax_get_range",
            data:datas,
            {#dataType: "json",#}
            success: function(data){

                if (data == "1"){
                }
                if (data == "default"){
                  layer.open({
                  type: 1
                  ,area: ['300px', '150px']
                  ,title: '选择错误'
                  ,shade: 0.6
                  ,maxmin: true
                  ,anim: 1
                  ,content: '<div style="padding:30px;background:#b7b7b7">' + "<span style='margin-left:60px;color:red'><i>请正确选择当前选项<i></span>" +'</div>'
});
                }else {
                    var jsp = JSON.parse(data)
                    for (var i=0;i<jsp.length;i++){
                        $("#van").append("<option   name='"+ jsp[i] + "' value='"+jsp[i]+"' > "+jsp[i]+" </option>");
                    }
                }
            }
        })
    })



function alink(){
        var ac_name=$("#ac_name").val();
        var MySelect = $("#MySelect option:selected").attr("name");
        var selectip=$("#selectip").val();
        var command = $("#shell_command").val();
        var selectrange =$("#selectrange option:selected").attr("name");
        alert(ac_name)
        alert(MySelect)
        alert(selectip)
        alert(command)
        alert(selectrange)

    }
</script>

{% endblock %}

CrazyGril/task/templates/shell_add.html
{% extends "rudiment_index.html" %}
{% load staticfiles %}
{% load tz %}
{% block breadcrumb %}执行Shell
<span style="margin-left: 20px"></span>

<a href="/cmdb/idc_info"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="alert alert-info">
            <i class="fa fa-info-circle"></i> 以下填写只能是shell命令和参数。</br>
            <i class="fa fa-info-circle"></i> 以下操作会进行日志保存。</br>
            <span class="label label-danger"> 以下选择范围会根据选择方式自动获取。</span>

        </div>
    </div>

 <form  action="" name="splitf" method="post" class="form form-horizontal" id="form_ids" enctype="multipart/form-data" >
   {% csrf_token %}

<div class="row cl" style="display: none">
        <label class="form-label col-3"><span class="c-red">*</span>hidden</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="{{host_info.id}}" name="idc_id" />
        </div>
    </div>


    <div class="row cl">
        <label class="form-label col-3"><span  class="c-red">*</span>执行名称</label>
        <div class="formControls col-7">
                 <input type="text"   class="input-text form-control"  value="{{host_info.sn}}"  name="ac_name"  id="ac_name" />
        </div>
    </div>


   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>选择方式</label>
        <div class="formControls col-7">
            <select class="form-control" name="sele" id="MySelect">
                <option name="default">-------------</option>
                <option name="1">主机ip</option>
                <option name="2">机房</option>
                <option name="3">组</option>
            </select>
        </div>
    </div>



    <div  id = "selectrange" class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>选择范围</label>
        <div class="formControls col-7">
            <select class="form-control" name="rag" id="van" >

            </select>
        </div>
    </div>


      <div  id = "selectip"  style="display: none" class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>选择IP</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"   value=""   name="selectip"  />
        </div>
    </div>





       <div class="row cl">
        <label class="form-label col-3"><span class="c-red" >*</span>Shell  Command</label>
        <div class="formControls col-7">
            <textarea  id = "shell_command" name="shell_command" class="form-control" rows="5"></textarea>

        </div>
    </div>



      <div class="row cl">
        <label class="form-label col-3">上传shell脚本</label>
        <div class="formControls col-7">
            <a  class="input-text form-control btn btn-primary" onclick="alink()" modal-title="上传shell 文件" data-target="#add" data-toggle="modal" data-height="330" data-width="700"
               href="/task/upf">
                上传dockerfile -- {{ filename }}
            </a>
{#            <input type="text" class="input-text form-control"   value=""   name="upload_sh"  />#}
{#         <input type="file" class="input-text form-control btn btn-primary"   value=""   name="uploadf"  />#}
        </div>
    </div>


   <div id="add" class="modal hide fade " tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <span class="glyphicon glyphicon-fullscreen"></span>
                <span class="close" data-dismiss="modal" aria-hidden="true"><i class="glyphicon glyphicon-remove "></i></span>

                <h3>对话框标题</h3>
            </div>
            <div class="modal-body"></div>

        </div>



   <div class="row cl">
        <label class="form-label col-3"></label>
        <div class="formControls col-7">
        <button onclick="sub()" class="btn radius btn-primary ">执行<span class="glyphicon glyphicon-ok"></span></button>
            <span style="margin-left: 5px"></span>
        <button onclick="cancel()" class="btn radius btn-success " >取消<span class="glyphicon glyphicon-remove"></span></button>
        </div>
    </div>



</form>


<script>
    function cancel(){
        document.splitf.action="{% url 'task:shell_exe' %}";
        document.splitf.submit();
    }

     function sub(){
       $.ajax({
           type:"POST",
           url:"/task/because_accres",
           data:$("#form_ids").serialize(),
           async:false,
           success:function(datas){
               {#alert(datas);#}
                layer.open({
                  type: 1
                  ,area: ['300px', '150px']
                  ,title: '操作结果'
                  ,shade: 0.6
                  ,maxmin: true
                  ,anim: 1
                  ,content: '<span style="margin-left:50px">已执行，详细信息请返回列表页！</span>'
});
           }

       })


         {################################################################}
         var ac_name = $("#ac_name").val();
         var uploadf = $("#uploadf");
         var formFile = new FormData();
         var fileObj = $("#splitf").files[0];
         formFile.append("file", fileObj)
         formFile.append("ac_name", ac_name)
          alert("开始上传")
         $.ajax({

              type:"POST",
              url:"/task/ajax_show_tasks",
              data:uploadf,
              processData:false,
              contentType:false,
             success:function(datas){
                   alert("上传成功")
                  console.log("123")
             }


         });
         get();
         {##################################################################}

    }




    $("#MySelect").change(function(){
        $("#van").empty();
        var opt = $("#MySelect option:selected").attr("name");
         $("#selectip").hide()
         $("#selectrange").show()

        if (opt == "1"){
             $("#selectip").show()
             $("#selectrange").hide()
        }


        var datas = {
            'csrftoken': csrftoken,
            'range':opt
        };
        $.ajax({
            type:"POST",
            url:"/task/ajax_get_range",
            data:datas,
            {#dataType: "json",#}
            success: function(data){

                if (data == "1"){
                }
                if (data == "default"){
                  layer.open({
                  type: 1
                  ,area: ['300px', '150px']
                  ,title: '选择错误'
                  ,shade: 0.6
                  ,maxmin: true
                  ,anim: 1
                  ,content: '<div style="padding:30px;background:#b7b7b7">' + "<span style='margin-left:60px;color:red'><i>请正确选择当前选项<i></span>" +'</div>'
});
                }else {
                    var jsp = JSON.parse(data)
                    for (var i=0;i<jsp.length;i++){
                        $("#van").append("<option   name='"+ jsp[i] + "' value='"+jsp[i]+"' > "+jsp[i]+" </option>");
                    }
                }
            }
        })
    })



function alink(){
        var ac_name=$("#ac_name").val();
        var MySelect = $("#MySelect option:selected").attr("name");
        var selectip=$("#selectip").val();
        var command = $("#shell_command").val();
        var selectrange =$("#selectrange option:selected").attr("name");
        alert(ac_name)
        alert(MySelect)
        alert(selectip)
        alert(command)
        alert(selectrange)

    }
</script>

{% endblock %}

CrazyGril/task/templates/show_tasks.html
{% extends "rudiment_index.html" %}
{% load staticfiles %}
{% load tz %}
{% block breadcrumb %}任务列表
<span style="margin-left: 20px"></span>
<a href="/cmdb/wechat"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>
{% endblock %}

{% block content %}
<style type="text/css">
.query-title {
    height:32px;
    line-height:32px;
    text-align: right;
}
.query-input {
    width: 200px!important;
}
</style>


     <div class="row">
        <form class="form form-inline" action="/docker/search_build_image" method="POST">
             {% csrf_token %}
            <div class="well well-sm">
                主机名称:&nbsp;<input type="text" name="newimage" value="{{ newimage }}" class="form-control  input-sm" size="10" />
                主机ip:&nbsp;        <input type="text" name="version" value="{{ version }}" class="form-control  input-sm" size="10" />
                <div class="btn-group">
                    <input type="submit" class="btn btn-primary btn-sm" onclick="showLoading()"  value="搜索"/>
                </div>
            </div>
        </form>
    </div>

        <div>
<div class="row">
        <div class="alert alert-info">
            <i class="fa fa-info-circle"></i> 以下显示任务执行后的状态。</br>
            <i class="fa fa-info-circle"></i> 以下任务都放在任务队列，如果执行长,可能不能及时返回结果。</br>
{#            <i class="fa fa-info-circle"></i> 如不需要续期，请到 <a target="_blank" href="http://workflow.cyou-inc.com">OA系统</a> 中进行虚机退回表单操作。</br>#}
            <span class="label label-danger"> 一下任务信息会长期存在。</span>
        </div>
    </div>
        </div>
<div style="margin-top: 10px"></div>

<div id="edit" class="modal hide fade " tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <span class="glyphicon glyphicon-fullscreen"></span>
        <span class="close" data-dismiss="modal" aria-hidden="true"><i class="glyphicon glyphicon-remove "></i></span>

        <h3>对话框标题</h3>
    </div>
    <div class="modal-body"></div>
</div>

        <div class="row">
            <table class="table" id="table" data-toggle="table"></table>
        </div>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#table").bootstrapTable({
                    showRefresh: true,
                    clickToSelect: true,
                    showColumns: true,
                    showToggle: true,
                    sortable: true,
                    pagination: true,
                    striped: true,

                    url: '{% url "task:ajax_show_tasks" %}',
                    columns: [{
                        field: "rownum",
                        checkbox: "true"
                    },{
                        field: "task_id",
                        title: "任务id"
                    }, {
                        field: "status",
                        title: "任务状态",
                        sortable: true
                    }, {
                        field: "content_type",
                        title: "任务返回格式",
                        sortable: true
                    }, {
                        field: "content_encoding",
                        title: "任务返回编码",
                        sortable: true
                    },{
                        field: "result",
                        title: "任务返回结果",
                        sortable: true
                    }, {
                        field: "traceback",
                        title: "执行异常",
                        sortable: true
                    },{
                        field: "date_done",
                        title: "执行完成时间",
                        sortable: true
                    }]
                });
            });
            </script>




{% endblock %}

CrazyGril/task/templates/upf.html
<form action="/task/tun_upf" method="post" class="form form-horizontal" id="form_validation" enctype="multipart/form-data">
    {% csrf_token %}




    <div class="row cl">
        <label class="form-label col-3">上传文件</label>
        <div class="formControls col-7">
             <input type="file" class="input-text form-control btn btn-success"   value=""   name="uploadf"  />
        </div>
    </div>


{#<div class="row cl">#}
{#        <label class="form-label col-3">创建时间：</label>#}
{#        <div class="formControls col-7">#}
{#            <input type="text" class="input-text form-control" value="{{ upload_time }}" name="upload_time" readonly />#}
{#        </div>#}
{#    </div>#}


    <div class="modal-footer">
        <button type="submit" class="btn radius btn-primary">确定</button>
        <button class="btn radius " data-dismiss="modal" aria-hidden="true">关闭</button>
    </div>
</form>