CrazyGril/CrazyGril/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'CrazyGril.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('rudiment.urls', namespace='rudiment')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^docker/', include('docker.urls', namespace='docker')),
    url(r'^conf/', include('conf.urls', namespace='conf')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^task/', include('task.urls', namespace='task')),
]

CrazyGril/api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'get_asset_info', 'api.views.get_asset_info', name='get_asset_info'),
    url(r'get_sysInfo', 'api.views.get_sysInfo', name='get_sysInfo'),
    url(r'^get_dockerInfo', 'api.views.get_dockerInfo', name='get_dockerInfo'),
    url(r'^test', 'api.views.test', name='test'),
    url(r'^auto_git', 'api.views.auto_git', name='auto_git'),
    url(r'^get_dockerStats', 'api.views.get_dockerStats', name='get_dockerStats'),
    url(r'^auto_git2', 'api.views.auto_git2', name='auto_git2'),
   )

CrazyGril/docker/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
   url(r'^image_build', 'docker.views.image_build', name='image_build'),
   url(r'^build_add', 'docker.views.build_add', name='build_add'),
   url(r'^image_create_add', 'docker.views.image_create_add', name='image_create_add'),
   url(r'^image_delete', 'docker.views.image_delete', name='image_delete'),
   url(r'^image_edit', 'docker.views.image_edit', name='image_edit'),
   url(r'^upload_dockerfile', 'docker.views.upload_dockerfile', name='upload_dockerfile'),
   url(r'^search_build_image', 'docker.views.search_build_image', name='search_build_image'),
   url(r'^update_images', 'docker.views.update_images', name='update_images'),
   url(r'^show_con', 'docker.views.show_con', name='show_con'),
   url(r'^container_show', 'docker.views.container_show', name='container_show'),
   url(r'^show_stats', 'docker.views.show_stats', name='show_stats'),
   url(r'^ajax_docker_stats', 'docker.views.ajax_docker_stats', name='ajax_docker_stats'),
   url(r'^query_stat', 'docker.views.query_stat', name='query_stat'),
   url(r'^ajax_query_stats/(?P<hostip>\d+)/$', 'docker.views.ajax_query_stats', name='ajax_query_stats'),
   url(r'^docker_echarts', 'docker.views.docker_echarts', name='docker_echarts'),
   url(r'^Ajax_getInfo', 'docker.views.Ajax_getInfo', name='Ajax_getInfo'),
   url(r'^container_e', 'docker.views.container_e', name='container_e'),
   url(r'^Ajax_tt', 'docker.views.Ajax_tt', name='Ajax_tt'),
   url(r'^t_get_conec', 'docker.views.t_get_conec', name='t_get_conec'),
   url(r'^search_c', 'docker.views.search_c', name='search_c'),




   # url(r'^query_stat/(?P<hostip>\d+)/$', 'docker.views.query_stat', name='query_stat'),
   # url(r'^Elk_Create', 'rudiment.views.Elk_Create', name='Elk_Create'),

   )

CrazyGril/docker/views.py
#-*- coding:utf-8 -*-
import json
import logging
import traceback
import datetime
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.template import RequestContext
from django.shortcuts import render
from docker.models import dockerfiles,dockerHost,DockerStat,dockerStats
from common.get_all_images import get_images,build_image,del_image
from common.get_init_catalog import get_init_names,get_dockerfile_info
from common.utils import get_base_image,page_split,get_host_info
from common.change_image_info import image_change_vt
# from models import dockerStats
import configparser as fg
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
import time
import os

# Create your views here.

def image_delete(request):
    if request.method == "POST":
        try:
            print request.body
            imagede = request.POST.get("imagede")
            delidimage = imagede.encode("utf-8")
            imageid = delidimage.split(" ")[0].strip()
            image_na = dockerfiles.objects.filter(id=imageid).values()
            name = image_na[0]["newimage"]
            print "image_na,name"
            print image_na,name
            dockerfiles.objects.filter(id=imageid).delete()
            del_image(name)
            return redirect('/docker/image_build')
        except Exception:
            print traceback.format_exc()
            return traceback.format_exc()
    if request.method == "GET":
        try:
            imagede = request.GET.get("imagede")
            delidimage = imagede.encode("utf-8")
            imageid = delidimage.split(" ")[0].strip()
            return render(request, "confirm_del.html",locals())
        except Exception:
            print traceback.format_exc()
            return HttpResponse(traceback.format_exc())

def search_build_image(request):

    if request.method == "POST":
        print request.body
        maintainer = request.POST.get("maintainer").strip()
        version = request.POST.get("version").strip()
        newimage = request.POST.get("newimage").strip()
        # print maintainer,version,newimage
        print "maintainer:" + maintainer
        print "version:" + version
        print "newimage:" + newimage
        import socket
        # myname = socket.getfqdn(socket.gethostname())
        # myaddr = socket.gethostbyname(myname)
        # print myname
        # print myaddr
        if maintainer and not version and not newimage:
            maintainer = maintainer
            all_data = dockerfiles.objects.filter(maintainer__icontains=maintainer).values()
            print all_data

            ########
            pages = '1'
            data = page_split(all_data, pages, nu=4)
            all_data = data[0]
            paginator = data[1]
            ########
            res = get_host_info()
            hostip = res[1]
            return render(request,"image_build.html",locals())
            # return HttpResponse()
        if not maintainer and  version and not newimage:
            version=version
            all_data = dockerfiles.objects.filter(version__icontains=version).values()
            print all_data

            ########
            pages = '1'
            data = page_split(all_data, pages, nu=4)
            all_data = data[0]
            paginator = data[1]
            ########
            res = get_host_info()
            hostip = res[1]
            return render(request, "image_build.html", locals())
        if not maintainer and  not version and  newimage:
            newimage=newimage
            all_data = dockerfiles.objects.filter(newimage__icontains=newimage).values()
            print all_data

            ########
            pages = '1'
            data = page_split(all_data, pages, nu=4)
            all_data = data[0]
            paginator = data[1]
            ########
            res = get_host_info()
            hostip = res[1]
            return render(request, "image_build.html", locals())
        if  maintainer and  version and not newimage:
            maintainer=maintainer
            version=version
            all_data = dockerfiles.objects.filter(newimage__icontains=newimage,version__icontains=version).values()
            print all_data
            ########
            pages = '1'
            data = page_split(all_data, pages, nu=4)
            all_data = data[0]
            paginator = data[1]
            ########
            res = get_host_info()
            hostip = res[1]
            return render(request, "image_build.html", locals())
        if not  maintainer and  version and  newimage:
            version = version
            newimage=newimage
            all_data = dockerfiles.objects.filter(maintainer__icontains=maintainer,version__icontains=version).values()
            print all_data
            ########
            pages = '1'
            data = page_split(all_data, pages, nu=4)
            all_data = data[0]
            paginator = data[1]
            ########
            res = get_host_info()
            hostip = res[1]
            return render(request, "image_build.html", locals())
        if maintainer and version and newimage:
            all_data = dockerfiles.objects.filter(version__icontains=version, maintainer__icontains=maintainer, newimage__icontains=newimage).values()
            version = version
            newimage = newimage
            maintainer =maintainer
            ########
            pages = '1'
            data = page_split(all_data, pages, nu=4)
            all_data = data[0]
            paginator = data[1]
            ########
            res = get_host_info()
            hostip = res[1]
            return render(request, "image_build.html", locals())
        if  not maintainer and not version and not newimage:
            print "在这吗？"
            all_data = dockerfiles.objects.all().values()
            print "all_data"
            print all_data
            ########
            pages = '1'
            data = page_split(all_data, pages, nu=4)
            all_data = data[0]
            paginator = data[1]
            ########
            res = get_host_info()
            hostip = res[1]
            return render(request, "image_build.html", locals())

    if request.method == "GET":
        print "GET------------------"
        dockerfile = dockerfiles.objects.all().values()
        res = get_host_info()
        hostip = res[1]
        return render(request, "image_build.html", locals())



def build_add(request):
    try:
        if request.method == "GET":
            command = "docker images"
            dic={}
            lis=[]
            images = get_images(command)
            nu = 0
            for i in images:
                dic[nu]= i
                nu = nu + 1
            print "========="
            print dic

            requestuser = request.user.username

            return render(request, "image_build_add.html",locals())
        if request.method == "POST":

            return render(request, "image_build_add.html")
    except Exception:
        print traceback.format_exc()




def image_create_add(request):
    if request.method == "GET":
        return  HttpResponse("get 形式！")
    if request.method == "POST":
        try:
            print "====================="
            print request.body
            # images = request.POST.get("images")
            requestUser = request.user.username
            base_image = request.POST.get("images")
            maintainer = request.POST.get("user", requestUser)
            version = request.POST.get("version", "latest")
            command = request.POST.get("command")
            newimage = request.POST.get("newimage")
            msg = request.POST.get("msg", "msg")

            catalog_name = base_image.split(":")[0].split("/")[-1]

            #####################################
            # 获取初始化dockerfile 目录
            ######################################
            init_conf = get_init_names()
            config = fg.RawConfigParser()
            with open(init_conf, "r") as file:
                config.read_file(file)
                dockerfile_catalog = config.get("dockerfile", "dockerfile_catalog")
                df = dockerfile_catalog +"/" + newimage
            if os.path.exists(df):
                pass
            else:
                os.makedirs(df)
            dfs = df + "/" + "dockerfile"
            print "dfs"
            print dfs
            print "format"
            print "FROM {0}\nMAINTAINER {1}\n{2}".format(base_image, maintainer, command)
            with open(dfs, "w") as f:
                f.write("FROM {0}\nMAINTAINER {1}\n{2}".format(base_image, maintainer, command))
            status = 1
            res = build_image(newimage, version, df)
            print "res"
            print res
            if res == 1:
                try:
                    dockerfile = dockerfiles()
                    dockerfile.newimage = newimage
                    dockerfile.base_image = base_image
                    dockerfile.maintainer = maintainer
                    dockerfile.version = version
                    dockerfile.msg = msg
                    dockerfile.status = status
                    # dockerfile.newimage = newimage
                    dockerfile.save()
                    return redirect("/docker/image_build")
                    # return render(request, "image_build.html")
                except Exception:
                    print traceback.format_exc()
                    return HttpResponse(traceback.format_exc())
            else:
                return  HttpResponse("创建失败，请查看服务器！")
        except Exception:
            print traceback.format_exc()




def upload_dockerfile(request):
    if request.method == "GET":

CrazyGril/docker/templates/confirm_del.html
<form action="/docker/image_delete" method="post" class="form form-horizontal" id="form_validation">
    {% csrf_token %}


    <!--<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">-->
	<!--<div class="modal-dialog">-->
		<!--<div class="modal-content">-->
			<!--<div class="modal-header">-->
				<!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">-->
					<!--&times;-->
				<!--</button>-->
				<!--<h4 class="modal-title" id="myModalLabel">-->
					<!--模态框（Modal）标题-->
				<!--</h4>-->
			<!--</div>-->
			<!--<div class="modal-body">-->
				<!--在这里添加一些文本-->
			<!--</div>-->
			<!--<div class="modal-footer">-->
				<!--<button type="button" class="btn btn-default" data-dismiss="modal">关闭-->
				<!--</button>-->
				<!--<button type="button" class="btn btn-primary">-->
					<!--提交更改-->
				<!--</button>-->
			<!--</div>-->
		<!--</div>&lt;!&ndash; /.modal-content &ndash;&gt;-->
	<!--</div>&lt;!&ndash; /.modal &ndash;&gt;-->
<!--</div>-->



<div class="text-center">
        <input type="text" name="imagede" class="hidden" value="{{ imagede }}"/>
        <button type="submit" class="btn radius btn-primary" style="margin: 10px 5px">删除</button>
        <button class="btn radius " data-dismiss="modal" aria-hidden="true" style="margin: 10px  5px" >关闭</button>

    </div>

</form>

CrazyGril/docker/templates/image_build_add.html
<form action="{% url 'docker:image_create_add' %}" method="post" class="form form-horizontal" id="form_validation">
    {% csrf_token %}

     <!--<div class="row cl" style="display: none">-->
        <!--<label class="form-label col-3"><span class="c-red">*</span>Dockerfile catalog:</label>-->
        <!--<div class="formControls col-7">-->
            <!--<input type="text" class="input-text form-control  validate[required]" value="" name="dockerfilename" />-->
        <!--</div>-->
    <!--</div>-->

    <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>基础镜像(From):</label>
        <div class="formControls col-7">
            <select class="form-control input-text select2" name="images" id="images">
                <option value="1" style="color: #b6b6b6" disabled selected>请选择镜像（づ￣3￣）づ╭❤～</option>
                {% for k,v in dic.items %}
                <option value="{{v}}">{{v}}</option>
                <!--{{k}}-->
                <!--{{v}}}-->
                {% endfor %}
                <!--{% for image in images %}-->
                    <!--&lt;!&ndash;{% if image %}&ndash;&gt;-->
                    <!--<option value="{{image}}">{{image}}</option>-->
                    <!--&lt;!&ndash;{% else %}&ndash;&gt;-->
                    <!--&lt;!&ndash;<option value="{{image}}">{{image}}</option>&ndash;&gt;-->
                    <!--&lt;!&ndash;{% endif%}&ndash;&gt;-->
                <!--{% endfor%}-->
                <!--<option value="2">centos6.6</option>-->
                <!--<option value="3">ubuntu14.04</option>-->
                <!--<option value="5">busybox 测试用</option>-->
                <!--<option value="4" style="color: #b6b6b6" disabled>其他镜像...正在制作中（づ￣3￣）づ╭❤～。。。。</option>-->
            </select>
        </div>
    </div>





    <div class="row cl">
        <label class="form-label col-3">维护者(MAINTAINER):</label>
        <div class="formControls col-7">

            {% if requestuser %}
            <input type="text" class="input-text form-control" value="{{requestuser}}" name="user" />
            {% else %}
            <input type="text" class="input-text form-control" value="" name="user" />
            {% endif %}

        </div>
    </div>




  <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>版本号(version)</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control validate[required]" style="color: #b6b6b6" value="latest"  name="version" />

        </div>
    </div>


 <div class="row cl">

        <label class="form-label col-3"><span class="c-red">*</span>命令(command):</label>
        <div class="formControls col-7">
            <textarea name="command"  required cols="10" rows="5"   width="100%"  class="form-control"  ></textarea>
        </div>
    </div>
    <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>新镜像名称</label>
        <div class="formControls col-7">
             <input type="text"  class="input-text form-control" style="text-transform:lowercase"  onkeyup="this.value=this.value.replace(/[^a-zA-Z]/g,'')" value=""  name="newimage"  />
        </div>
    </div>




    <div class="row cl">
        <label class="form-label col-3">创建时间</label>
        <div class="formControls col-7">
             <input type="date"  class="input-text form-control" style="color: #b6b6b6" name="createtime" />
        </div>
    </div>


    <div class="row cl">
        <label class="form-label col-3">备注信息</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"  style="color: #b6b6b6" value="备注信息"  name="msg" />
        </div>
    </div>


    <div class="modal-footer">
        <button type="submit" class="btn radius btn-primary">创建！</button>
        <button class="btn radius " data-dismiss="modal" aria-hidden="true">关闭</button>
    </div>

    <!--<script type="text/javascript">-->
        <!--$(function(){-->
            <!--jQuery("#form_validation").validationEngine({});-->
            <!--$.get("",-->
                <!--function(data){-->
                    <!--if(data){-->
                        <!--for(var i=0;i<data.length;i++){-->
                            <!--$('#objectiveIdc').append("<option value='"+data[i]+"'>"+data[i]+"</option>");-->
                        <!--}-->
                    <!--}-->
                <!--}, "json");-->
        <!--});-->

        <!--$("#objectiveIdc").change(function () {-->
            <!--var objectiveIdc = $(this).children('option:selected').val();-->
            <!--hostGroupIp = $("input[name='hostGroupIp']").val();-->
            <!--aclNumber = $("input[name='aclNumber']").val();-->
            <!--console.log(hostGroupIp, aclNumber);-->
            <!--var url = "";-->
            <!--$.post(url, {'objectiveIdc': objectiveIdc, 'csrftoken': csrftoken},-->
                    <!--function (data) {-->
                        <!--if (data["code"] == "0") {-->
                            <!--$("input[name='hostGroupIp']").val(data["data"]["host_group_ip"]);-->
                            <!--$("input[name='aclNumber']").val(data["data"]["acl_number"]);-->
                            <!--$("input[name='ruleNumber']").val(data["data"]["rule_number"]);-->
                        <!--}-->
                        <!--else{-->
                            <!--$("input[name='ruleNumber']").val("内部异常错误");-->
                        <!--}-->
                    <!--}, "json");-->
        <!--});-->


        <!--$("input[name='hostGroupIp']").change(function () {-->
            <!--hostGroupIp = $("input[name='hostGroupIp']").val();-->
            <!--aclNumber = $("input[name='aclNumber']").val();-->
            <!--console.log(hostGroupIp, aclNumber);-->
            <!--var url = "";-->
            <!--$.post(url, {'hostGroupIp': hostGroupIp, 'aclNumber': aclNumber, 'csrftoken': csrftoken},-->
                    <!--function (data) {-->
                        <!--if (data["code"] == "0") {-->
                            <!--$("input[name='ruleNumber']").val(data["data"]);-->
                        <!--}-->
                        <!--else{-->
                            <!--$("input[name='ruleNumber']").val("内部异常错误");-->
                        <!--}-->
                    <!--}, "json");-->
        <!--});-->

        <!--$("input[name='aclNumber']").change(function () {-->
            <!--hostGroupIp = $("input[name='hostGroupIp']").val();-->
            <!--aclNumber = $("input[name='aclNumber']").val();-->
            <!--console.log(hostGroupIp, aclNumber);-->
            <!--var url = "";-->
            <!--$.post(url, {'hostGroupIp': hostGroupIp, 'aclNumber': aclNumber, 'csrftoken': csrftoken},-->
                    <!--function (data) {-->
                        <!--console.log(data);-->
                        <!--if (data["code"] == "0") {-->
                            <!--console.log(data["data"]);-->
                            <!--$("input[name='ruleNumber']").val(data["data"]);-->
                        <!--}-->
                        <!--else{-->
                            <!--$("input[name='ruleNumber']").val("内部异常错误");-->
                        <!--}-->
                    <!--}, "json");-->
        <!--});-->
    <!--</script>-->
</form>

CrazyGril/docker/templates/show_stats.html
{% extends "rudiment_index.html" %}
{% load staticfiles %}
{% load tz %}
{% block breadcrumb %}容器监控信息
<span style="margin-left: 20px"></span>
<a href="/cmdb/wechat"><span><button class="btn radius btn-success " ><span class="glyphicon glyphicon-backward"></span>返回</button></span></a>
{% endblock %}

{% block content %}
<style type="text/css">
.query-title {
    height:32px;
    line-height:32px;
    text-align: right;
}
.query-input {
    width: 200px!important;
}
</style>


     <div class="row">
        <form class="form form-inline" action="/docker/search_build_image" method="POST">
             {% csrf_token %}
            <div class="well well-sm">
                主机名称:&nbsp;<input type="text" name="newimage" value="{{ newimage }}" class="form-control  input-sm" size="10" />
                主机ip:&nbsp;        <input type="text" name="version" value="{{ version }}" class="form-control  input-sm" size="10" />
                <div class="btn-group">
                    <input type="submit" class="btn btn-primary btn-sm" onclick="showLoading()"  value="搜索"/>
                </div>
            </div>
        </form>
    </div>

        <div>
<div class="row">
        <div class="alert alert-info">
            <i class="fa fa-info-circle"></i> 以下表格显示容器的状态信息。</br>
            <i class="fa fa-info-circle"></i> 以下容器资源都是没有限制。</br>
{#            <i class="fa fa-info-circle"></i> 如不需要续期，请到 <a target="_blank" href="http://workflow.cyou-inc.com">OA系统</a> 中进行虚机退回表单操作。</br>#}
            <span class="label label-danger"> 以下容器的信息都是建立在共享宿主机资源的情况下的展示。</span>
        </div>
    </div>
        </div>
<div style="margin-top: 10px"></div>

<div id="edit" class="modal hide fade " tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <span class="glyphicon glyphicon-fullscreen"></span>
        <span class="close" data-dismiss="modal" aria-hidden="true"><i class="glyphicon glyphicon-remove "></i></span>

        <h3>对话框标题</h3>
    </div>
    <div class="modal-body"></div>
</div>

        <div class="row">
            <table class="table" id="table" data-toggle="table"></table>
        </div>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#table").bootstrapTable({
                    showRefresh: true,
                    clickToSelect: true,
                    showColumns: true,
                    showToggle: true,
                    sortable: true,
                    pagination: true,
                    striped: true,

                    url: '{% url "docker:ajax_docker_stats" %}',
                    columns: [{
                        field: "rownum",
                        checkbox: "true"
                    },{
                        field: "hostname",
                        title: "主机名"
                    }, {
                        field: "container",
                        title: "CONTAINER",
                        sortable: true
                    }, {
                        field: "cpu",
                        title: "CPU %",
                        sortable: true
                    }, {
                        field: "mem_ul",
                        title: "MEM USAGE / LIMIT",
                        sortable: true
                    },{
                        field: "mem",
                        title: "MEM %",
                        sortable: true
                    }, {
                        field: "net_io",
                        title: "NET I/O",
                        sortable: true
                    },{
                        field: "block_io",
                        title: "BLOCK I/O",
                        sortable: true
                    }, {
                        field: "ids",
                        title: "容器资源图表",
                        sortable: true,
                        formatter:function(value,row,index){
                            {#alert(value)#}
                            return[
                                '<a  href="/docker/container_e?container_id='+ value +'" style="text-decoration:none">'+  '<span class="glyphicon glyphicon-asterisk"> </sapn>' +'</i> </a>'
                            ]
                }
                    }]
                });
            });
            </script>




{% endblock %}

CrazyGril/docker/templates/upload_dockerfile.html
<form action="{% url 'docker:upload_dockerfile' %}" method="post" class="form form-horizontal" id="form_validation" enctype="multipart/form-data" >
   {% csrf_token %}

<div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>新镜像名称:</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control" value="" name="newimage" required="required" />
        </div>
    </div>

 <!--<div class="row cl">-->
        <!--<label class="form-label col-3"><span class="c-red">*</span>版本</label>-->
        <!--<div class="formControls col-7">-->
             <!--<input type="text"  class="input-text form-control" style="color: #b6b6b6" name="version" required="required" />-->
        <!--</div>-->
    <!--</div>-->


 <!--<div class="row cl">-->
        <!--<label class="form-label col-3">维护者(MAINTAINER):</label>-->
        <!--<div class="formControls col-7">-->
            <!--<input type="text" class="input-text form-control" value="{{request_user}}" name="maintainer" />-->
        <!--</div>-->
    <!--</div>-->



   <div class="row cl">
        <label class="form-label col-3"><span class="c-red">*</span>创建时间</label>
        <div class="formControls col-7">
             <input type="date"  class="input-text form-control" style="color: #b6b6b6" name="createtime" />
        </div>
    </div>


    <div class="row cl">
        <label class="form-label col-3">备注信息</label>
        <div class="formControls col-7">
            <input type="text" class="input-text form-control"  style="color: #b6b6b6" value=""  name="msg"  placeholder="备注信息！٩(๑❛ᴗ❛๑)۶"/>
        </div>
    </div>

    <div class="row cl">
        <label class="form-label col-3">选择文件:</label>
        <div class="formControls col-7">
            <a href='javascript:void(0);' class="blueButton" style="position: absolute;
                display: block;
                width: 100px;
                height: 25px;
                background-color: #00b3ee;
                color: #fff;
                text-decoration: none;
                text-align: center;
                font:normal normal normal 16px/23px 'Microsoft YaHei';
                cursor: pointer;
                border-radius: 4px;">选择文件</a>
        <input type="file" class="myFileUpload" name="upload_dockerfile" style="position: absolute;
                display: block;
                width: 100px;
                height: 40px;
                opacity: 0;" required="required"/>
        <div class="show" style="position: absolute;
                top:40px;
                width: 100%;
                height: 30px;
                font:normal normal normal 14px/30px 'Microsoft YaHei';"></div>

        </div>
    </div>



    <div class="modal-footer">
        <button type="submit" class="btn radius btn-primary">创建！</button>
        <button class="btn radius " data-dismiss="modal" aria-hidden="true">关闭</button>
    </div>

<!--{#    <script type="text/javascript">#}-->
<!--{#         $(document).ready(function()#}-->
<!--{#    {#}-->
<!--{#        $(".myFileUpload").change(function()#}-->
<!--{#        {#}-->
<!--{#            var arrs=$(this).val().split('\\');#}-->
<!--{#            var filename=arrs[arrs.length-1];#}-->
<!--{#            $(".show").html(filename);#}-->
<!--{#        });#}-->
<!--{#    });#}-->
<!--{#    </script>#}-->
</form>